### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by pouledodue** [dweiss96/json_serializable_generator#1]
Hi
Can you do a Flutter example 
Something I can just open in vscode and run and it will work out-of-the-box

**Comment by dweiss96** [comment]
What do you mean with "battery-included"?

**Comment by pouledodue** [comment]
fixed

**Comment by dweiss96** [comment]
Can you please verify that the added example is sufficient to help you?

**Comment by Randle-Lanre** [comment]
I believe op has found his solution, it would be great if you can share the link to the solution that worked for you, that being said you could take a look at this package https://pub.dev/packages/dart_json_mapper

**Comment by dweiss96** [comment]
I marked the issue as stale and will merge the PR and close this issue in two days.
